global:
  scrape_interval: 5s

scrape_configs:
  - job_name: payment-saga
    static_configs:
      - targets:
          - orchestrator:8080
          - wallet:8080
          - risk:8080
          - notification:8080
